# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operaciones.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='operaciones.proto',
  package='practica5',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11operaciones.proto\x12\tpractica5\"5\n\x0f\x43\x61mposDeEntrada\x12\x10\n\x08\x65ntrada1\x18\x01 \x01(\t\x12\x10\n\x08\x65ntrada2\x18\x02 \x01(\t\"!\n\x0e\x43\x61mposDeSalida\x12\x0f\n\x07salida1\x18\x01 \x01(\t2\xe2\x04\n\x0bOperaciones\x12=\n\x04\x41uth\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\x12?\n\x06\x43reate\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\x12?\n\x04Read\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida0\x01\x12\x42\n\x05Write\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00(\x01\x12\x41\n\x06Remove\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00\x12\x41\n\x06Rename\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00\x12@\n\x05Mkdir\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00\x12@\n\x05Rmdir\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00\x12\x44\n\x07Readdir\x12\x1a.practica5.CamposDeEntrada\x1a\x19.practica5.CamposDeSalida\"\x00\x30\x01\x62\x06proto3'
)




_CAMPOSDEENTRADA = _descriptor.Descriptor(
  name='CamposDeEntrada',
  full_name='practica5.CamposDeEntrada',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entrada1', full_name='practica5.CamposDeEntrada.entrada1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entrada2', full_name='practica5.CamposDeEntrada.entrada2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=85,
)


_CAMPOSDESALIDA = _descriptor.Descriptor(
  name='CamposDeSalida',
  full_name='practica5.CamposDeSalida',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='salida1', full_name='practica5.CamposDeSalida.salida1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['CamposDeEntrada'] = _CAMPOSDEENTRADA
DESCRIPTOR.message_types_by_name['CamposDeSalida'] = _CAMPOSDESALIDA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CamposDeEntrada = _reflection.GeneratedProtocolMessageType('CamposDeEntrada', (_message.Message,), {
  'DESCRIPTOR' : _CAMPOSDEENTRADA,
  '__module__' : 'operaciones_pb2'
  # @@protoc_insertion_point(class_scope:practica5.CamposDeEntrada)
  })
_sym_db.RegisterMessage(CamposDeEntrada)

CamposDeSalida = _reflection.GeneratedProtocolMessageType('CamposDeSalida', (_message.Message,), {
  'DESCRIPTOR' : _CAMPOSDESALIDA,
  '__module__' : 'operaciones_pb2'
  # @@protoc_insertion_point(class_scope:practica5.CamposDeSalida)
  })
_sym_db.RegisterMessage(CamposDeSalida)



_OPERACIONES = _descriptor.ServiceDescriptor(
  name='Operaciones',
  full_name='practica5.Operaciones',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=733,
  methods=[
  _descriptor.MethodDescriptor(
    name='Auth',
    full_name='practica5.Operaciones.Auth',
    index=0,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='practica5.Operaciones.Create',
    index=1,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='practica5.Operaciones.Read',
    index=2,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='practica5.Operaciones.Write',
    index=3,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='practica5.Operaciones.Remove',
    index=4,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Rename',
    full_name='practica5.Operaciones.Rename',
    index=5,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Mkdir',
    full_name='practica5.Operaciones.Mkdir',
    index=6,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Rmdir',
    full_name='practica5.Operaciones.Rmdir',
    index=7,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Readdir',
    full_name='practica5.Operaciones.Readdir',
    index=8,
    containing_service=None,
    input_type=_CAMPOSDEENTRADA,
    output_type=_CAMPOSDESALIDA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERACIONES)

DESCRIPTOR.services_by_name['Operaciones'] = _OPERACIONES

# @@protoc_insertion_point(module_scope)
